version: "3.9"
services:
  template-dev:   # "template"を任意の名称に変更
    container_name: template-dev    # "template"を任意の名称に変更
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - ../:/workspace
